name: Hello
on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: greetings
        run: echo "Hello Dosto"

      - name: greet user
        run: echo "hello $USER"
  
  details:
    runs-on: ubuntu-latest
    steps:
      - name: print docker verison
        run: docker --version

      - name: print python version
        run: python --version
  
  
